set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]

set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS33} [get_ports CLK_100MHZ]
create_clock -period 10.000 -name sys_clk [get_ports CLK_100MHZ]

# PHY infra
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports JB4_P]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports phy_nrst]

# All candidate pins
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33} [get_ports pin_H18]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports pin_G18]
set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS33} [get_ports pin_H13]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS33} [get_ports pin_H14]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports pin_H16]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports pin_H17]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS33} [get_ports pin_J16]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS33} [get_ports pin_K14]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS33} [get_ports pin_F14]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS33} [get_ports pin_F15]
set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVCMOS33} [get_ports pin_J13]
set_property -dict {PACKAGE_PIN E14 IOSTANDARD LVCMOS33} [get_ports pin_E14]
set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS33} [get_ports pin_E15]

# LEDs
set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVCMOS33} [get_ports {LED[0]}]
set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33} [get_ports {LED[1]}]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33} [get_ports {LED[2]}]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33} [get_ports {LED[3]}]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS33} [get_ports {LED[4]}]
set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVCMOS33} [get_ports {LED[5]}]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33} [get_ports {LED[6]}]
set_property -dict {PACKAGE_PIN D17 IOSTANDARD LVCMOS33} [get_ports {LED[7]}]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS33} [get_ports {LED[8]}]
set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVCMOS33} [get_ports {LED[9]}]
set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVCMOS33} [get_ports {LED[10]}]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS33} [get_ports {LED[11]}]
set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVCMOS33} [get_ports {LED[12]}]
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports {LED[13]}]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports {LED[14]}]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports {LED[15]}]
