set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]

set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS33} [get_ports CLK_100MHZ]
create_clock -period 10.000 [get_ports CLK_100MHZ]

# 12 test pins in order
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33} [get_ports pin0]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports pin1]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports pin2]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports pin3]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports pin4]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets pin4_IBUF]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS33} [get_ports pin5]
set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS33} [get_ports pin6]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS33} [get_ports pin7]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports pin8]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports pin9]
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVCMOS33} [get_ports pin10]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVCMOS33} [get_ports pin11]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS33} [get_ports pin12]

set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVCMOS33} [get_ports {LED[0]}]
set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33} [get_ports {LED[1]}]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33} [get_ports {LED[2]}]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33} [get_ports {LED[3]}]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS33} [get_ports {LED[4]}]
set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVCMOS33} [get_ports {LED[5]}]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33} [get_ports {LED[6]}]
set_property -dict {PACKAGE_PIN D17 IOSTANDARD LVCMOS33} [get_ports {LED[7]}]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS33} [get_ports {LED[8]}]
set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVCMOS33} [get_ports {LED[9]}]
set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVCMOS33} [get_ports {LED[10]}]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS33} [get_ports {LED[11]}]
set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVCMOS33} [get_ports {LED[12]}]
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports {LED[13]}]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports {LED[14]}]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports {LED[15]}]
